name: Daily Bot Post (Gemini)

on:
  schedule:
    # Публикует каждый день в 7:00 UTC (это 10:00 MSK)
    - cron: '0 7 * * *'
  
  # Позволяет запустить вручную из GitHub Actions
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Клонируем репозиторий
    - name: Checkout code
      uses: actions/checkout@v3
    
    # 2. Устанавливаем Python 3.11
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # 3. Кешируем зависимости (для ускорения)
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # 4. Устанавливаем зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot google-generativeai python-dotenv requests
    
    # 5. Запускаем бота с переменными окружения
    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        python telegram_bot_gemini.py
      timeout-minutes: 10
    
    # 6. Логируем результат
    - name: Log status
      if: always()
      run: echo "Bot execution completed at $(date)"
